name: wire
description: Communication and data container layers library aimed to decouple UI from business logic
version: 1.4.7
homepage: https://github.com/WiresWare/wire_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.5
  build_web_compilers:
  build_runner:
  dart_style:
  lints: ^1.0.1
