name: wire
description: Wire is a publish-subscribe library, with static layer beneath, where responses associated with "keys" called - signals. Simplest possible API - add, remove and send.
version: 0.1.7
homepage: https://github.com/DQvsRA/Wire
author: Vladimir Cores (Minkin) <vladimir.cores@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
