name: wire
description: Wire is a publish-subscribe library, with static layer beneath, where responses associated with "keys" called - signals. Simplest possible API - add, remove and send.
version: 0.2.0
homepage: https://github.com/DQvsRA/Wire

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  build_web_compilers:
  build_runner:
