name: wire
description: Wire is a pub/sub library, event bus with data container, utilize only String key
version: 0.3.0
homepage: https://github.com/DQvsRA/Wire

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.6.0
  build_web_compilers:
  build_runner:
