name: wire
description: Communication and data container layers library aimed to decouple UI from business logic
version: 1.1.0
homepage: https://github.com/wire-toolkit/wire_dart

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.6.0
  build_web_compilers:
  build_runner:
