name: wire_example_angular_todo
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  glob: ^2.0.0
  angular: ^6.0.1
  wire: ^1.4.0
  wire_example_shared:
    path: ../_shared

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  build_web_compilers: ^2.12.0
  test: ^1.6.5

dependency_overrides:
  wire:
    path: ../..
