name: wire_example_angular_todo
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  glob: ^2.1.0
  angular: ^7.0.2
  wire: ^1.5.1
  wire_example_shared:
    path: ../_shared

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  test: ^1.22.0

dependency_overrides:
  wire:
    path: ../..
