name: wire_spa
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  wire: ^1.2.0
  states: ^1.0.0
  sporran: ^5.0.0
  tuple: ^1.0.3

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
