name: wire_example_counter
description: A web app that uses only native HTML components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  wire: ^1.5.4

dependency_overrides:
  wire:
    path: ../..

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  build_web_compilers: ^4.0.5
